export App from './App/App';
export Home from './Home/Home';
export People from './People/People';
export Projects from './Projects/Projects';
export Project from './Project/Project';
export Wordoflip from './Wordoflip/Wordoflip';
export Contact from './Contact/Contact';
export Guide from './Guide/Guide';
export NotFound from './NotFound/NotFound';
